### ISSUE TITLE
Memory leak on simple_performance

### ISSUE THREAD

**Issue by YuanYuYuan** [ZettaScaleLabs/rmw_zenoh#18]
![image](https://github.com/user-attachments/assets/7d4b0e7c-0ac4-4717-8e20-2a2ed4775649)

**Comment by YuanYuYuan** [comment]
This should be fixed by e9d0513.

![image](https://github.com/user-attachments/assets/df8f15fc-b860-48f5-b165-dc7bf3f84b8d)

**Comment by evshary** [comment]
@YuanYuYuan  Can we close this now? I suppose it was already fixed.

**Comment by YuanYuYuan** [comment]
Yes, let's close this.
