### ISSUE TITLE
Unable to run nav2 with rviz2 together

### ISSUE THREAD

**Issue by evshary** [ZettaScaleLabs/rmw_zenoh#32]
No matter in ROS2 rolling and jazzy, if we try to run nav2 with rviz2 together, rviz2 will crash

```shell
export TURTLEBOT3_MODEL=waffle
ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False
```

However, it will succeed if we run it separately. Note that we need to wait for rviz2 to be stable, and then run the nav2.

```shell
ros2 launch nav2_bringup rviz_launch.py
# Wait until we can control rivz2
export TURTLEBOT3_MODEL=waffle
ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False use_rviz:=False
```

**Comment by evshary** [comment]
We have some failures in the nav2 unit test item `nav2_system_tests`. Not sure whether it's related to the issue or not.

**Comment by imstevenpmwork** [comment]
I can confirm a similar behaviour from my side. If I run: 
```
ros2 launch nav2_bringup tb4_simulation_launch.py headless:=True use_rviz:=False
```
Wait until the nav2 logs stabilise, and then run:
```
rviz2
```
And manually add all the items step by step (including setting the initial pose), the demo works. Sometimes even launching all rviz config works
```
ros2 launch nav2_bringup rviz_launch.py
```

But trying to launch:
```
ros2 launch nav2_bringup tb4_simulation_launch.py headless:=False
```

Fails every time: `rviz2` crashes and `nav2` shutdowns

**Comment by evshary** [comment]
It's related to the issue
https://github.com/ros-navigation/navigation2/issues/4689
I've tried this patch and it works
https://github.com/ros-navigation/navigation2/pull/4717

**Comment by evshary** [comment]
The issue can be closed after backporting to Jazzy
https://github.com/ros-navigation/navigation2/pull/4725

**Comment by ajtudela** [comment]
Hi, it's now fixed in main and jazzy.

**Comment by evshary** [comment]
Hi @ajtudela Thank you so much for the backporting! I believe we can close the issue now.
